Fix set syntax in gstreamer.py
This caused a crash when starting to encode mp3s:

Traceback (most recent call last):
File "/usr/lib/soundconverter/python/soundconverter/ui.py", line 1309, in tags_read
self.converter.add(sound_file)
File "/usr/lib/soundconverter/python/soundconverter/gstreamer.py", line 762, in add
c.init()
File "/usr/lib/soundconverter/python/soundconverter/gstreamer.py", line 488, in init
encoder = self.encoders[self.output_type]()
File "/usr/lib/soundconverter/python/soundconverter/gstreamer.py", line 617, in add_mp3_encoder
if available_elements['xingmux'] and properties[self.mp3_mode][0]:
TypeError: 'set' object is not subscriptable

Original bug report is at https://bugs.archlinux.org/task/28150.

Signed-off-by: Jakob Gruber <jakob.gruber@gmail.com>